name: "Notion Burndown Chart"
description: "Generates Burndown Chart based on Scrum backlog in Notion database"
branding:
  icon: bar-chart-2
  color: green
inputs:
  NOTION_KEY:
    description: "Notion integration access token"
    required: true
  NOTION_DB_BACKLOG:
    description: "Notion Database ID of Sprint Backlog"
    required: true
  NOTION_DB_SPRINT_SUMMARY:
    description: "Notion Database ID of Sprint Summary"
    required: true
  NOTION_DB_DAILY_SUMMARY:
    description: "Notion Database ID of Daily Summary"
    required: true
  NOTION_PROPERTY_SPRINT:
    description: "Name of the property with the sprint number"
    required: true
  NOTION_PROPERTY_ESTIMATE:
    description: "Name of the property with the estimate"
    required: true
  NOTION_PROPERTY_PATTERN_STATUS_EXCLUDE:
    description: "Regex of the statuses of stories which are done"
    required: true
  INCLUDE_WEEKENDS:
    description: "True if weekends should be included in the chart, false otherwise."
    required: false
    default: "true"
  SPRINT_START:
    description: "True if it is the start of a new sprint, false otherwise. When true, a new entry will be created in the Sprint Summary database, and the sprint end date will be 14 days later (sprint start day excluded). Note that new sprint summary will not be created if today is still in the middle of the last sprint."
    required: false
    default: "false"
runs:
  using: "node16"
  main: "dist/index.js"
